### ISSUE TITLE
Not able to load ngx-gauge directive

### ISSUE THREAD

**Issue by saitejpoosarla** [ashish-chopra/ngx-gauge#6]
After importing NgxGaugeModule(imported after BrowserModule), trying to use the directive ngx-gauge throws the below error in my component.

`Error: Template parse errors:
'ngx-gauge' is not a known element:
1. If 'ngx-gauge' is an Angular component, then verify that it is part of this module.
2. If 'ngx-gauge' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
          <ion-card>

              [ERROR ->]<ngx-gauge >

              </ngx-gauge>
"): ng:///xxx/xxx.html@xx:xx
    at syntaxError (http://localhost:8100/build/vendor.js:130393:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:141631:19)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:155825:39)
    at http://localhost:8100/build/vendor.js:155744:62
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:155744:19)
    at http://localhost:8100/build/vendor.js:155631:19
    at Object.then (http://localhost:8100/build/vendor.js:130382:133)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:155630:26)
    at JitCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:155559:37)`

**Comment by saitejpoosarla** [comment]
Did not load the Module in the correct hierarchy. Closing Issue.
